package org.laioffer.planner.imports;

import org.laioffer.planner.entity.UserEntity;
import org.laioffer.planner.model.imports.ImportPlanRequest;
import org.laioffer.planner.model.imports.ImportPlanResponse;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

/**
 * Controller for importing plans from CRAG system.
 */
@RestController
@RequestMapping("/api")
public class ImportController {

    private static final Logger logger = LoggerFactory.getLogger(ImportController.class);

    private final ImportService importService;

    public ImportController(ImportService importService) {
        this.importService = importService;
    }

    /**
     * Import a complete travel plan from CRAG system.
     *
     * This endpoint receives POIs and plan data generated by CRAG conversation
     * and persists them to the database.
     *
     * @param request ImportPlanRequest containing POIs and plan structure
     * @param user Authenticated user from JWT token
     * @return HTTP 201 Created with itinerary ID and import statistics
     */
    @PostMapping("/import-plan")
    public ResponseEntity<ImportPlanResponse> importPlan(
            @Validated @RequestBody ImportPlanRequest request,
            @AuthenticationPrincipal UserEntity user) {

        // Authentication is now required - user must not be null
        if (user == null) {
            logger.warn("Import plan request without authentication");
            return ResponseEntity.status(HttpStatus.UNAUTHORIZED)
                    .body(new ImportPlanResponse(null, "Authentication required", 0, 0));
        }

        Long userId = user.getId();
        String userEmail = user.getEmail();

        logger.info("Import plan request from user: {}, CRAG session: {}",
                userEmail, request.getCragSessionId());

        // Optional: Check for duplicate import (idempotency)
        if (request.getCragSessionId() != null &&
                importService.isAlreadyImported(userId, request.getCragSessionId())) {
            logger.warn("Plan from CRAG session {} already imported for user {}",
                    request.getCragSessionId(), userEmail);
            return ResponseEntity.status(HttpStatus.CONFLICT)
                    .body(new ImportPlanResponse(null, "already_imported", 0, 0));
        }

        try {
            ImportPlanResponse response = importService.importPlan(userId, request);

            logger.info("Plan imported successfully. Itinerary: {}, POIs: {}",
                    response.getItineraryId(), response.getImportedPoisCount());

            return ResponseEntity.status(HttpStatus.CREATED).body(response);

        } catch (IllegalArgumentException e) {
            logger.error("Invalid import request: {}", e.getMessage());
            return ResponseEntity.badRequest()
                    .body(new ImportPlanResponse(null, "error: " + e.getMessage(), 0, 0));

        } catch (Exception e) {
            logger.error("Failed to import plan: {}", e.getMessage(), e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(new ImportPlanResponse(null, "error: " + e.getMessage(), 0, 0));
        }
    }
}
